### PR TITLE
One-Hot-Encoding

### PR DESCRIPTION
**Pull request by NiWaRe**
Hi, 
I just added a question and answer inc. a ressource and explanation of myself to the lesson2.md about one-hot-encoding.

### CODE REVIEW

**Comment by ishgirwan** [comment]
Hello NiWaRe, Thanks a lot for your pull request. I would have love to add this pull request. Although, as of now there are some issues with this pull request. I would recommend you to to do following: do a spell check, simplify your explanation and do simple formatting like in adding links. Thanks again for making this effort. :)

**Comment by NiWaRe** [comment]
Hey, alright just rewrote / reformatted everything. 
Is it fine now?

**Comment by ishgirwan** [comment]
Hi, it definitely is better now but I am unable to merge your pull request.  Getting this error: "This branch has conflicts that must be resolved". Can you try doing this: https://github.com/githubteacher/github-for-developers-sept-2015/issues/648

**Comment by NiWaRe** [comment]
Updated Pull-Request, should be mergable now!
(Added One-Hot-Encoding at the end of lesson2.md)

**Pull request merged**
